<?php

class PDFHelper
{
    /**
     * Generate Inspection Label PDF
     * Uses FPDF library
     */
    public static function generateLabel($extinguisherId, $data)
    {
        $filename = 'label_' . $data['serial_number'] . '.pdf';
        $path = __DIR__ . '/../uploads/labels/' . $filename;
        $qrLocalPath = __DIR__ . '/../uploads/qrcodes/' . $data['serial_number'] . '.png';

        // Ensure directory exists
        $dir = dirname($path);
        if (!file_exists($dir)) {
            mkdir($dir, 0777, true);
        }

        // Include FPDF
        $fpdfPath = __DIR__ . '/fpdf.php';
        if (file_exists($fpdfPath)) {
            require_once($fpdfPath);

            // Create PDF (Custom size: 100mm x 150mm)
            $pdf = new FPDF('P', 'mm', array(100, 150));
            $pdf->AddPage();

            // Draw Box
            $pdf->Rect(5, 5, 90, 140);

            // Title
            $pdf->SetFont('Helvetica', 'B', 16);
            $pdf->Cell(80, 10, 'FIRE EXTINGUISHER', 0, 1, 'C');
            $pdf->Cell(80, 5, 'INSPECTION LABEL', 0, 1, 'C');

            $pdf->Ln(10);

            // Details
            $pdf->SetFont('Helvetica', '', 12);
            $pdf->Cell(40, 10, 'Serial Number:', 0, 0);
            $pdf->SetFont('Helvetica', 'B', 12);
            $pdf->Cell(40, 10, $data['serial_number'], 0, 1);

            $pdf->SetFont('Helvetica', '', 12);
            $pdf->Cell(40, 10, 'Type:', 0, 0);
            $pdf->SetFont('Helvetica', 'B', 12);
            $pdf->Cell(40, 10, $data['type'] . ' (' . $data['capacity'] . ')', 0, 1);

            $pdf->SetFont('Helvetica', '', 12);
            $pdf->Cell(40, 10, 'Client:', 0, 0);
            $pdf->SetFont('Helvetica', 'B', 12);
            $pdf->Cell(40, 10, $data['client_name'], 0, 1);

            $pdf->Ln(5);
            $pdf->Line(10, $pdf->GetY(), 90, $pdf->GetY());
            $pdf->Ln(5);

            $pdf->SetFont('Arial', '', 12);
            $pdf->Cell(40, 10, 'Filling Date:', 0, 0);
            $pdf->Cell(40, 10, $data['filling_date'], 0, 1);

            $pdf->Cell(40, 10, 'Expiry Date:', 0, 0);
            $pdf->SetTextColor(200, 0, 0); // Red for expiry
            $pdf->Cell(40, 10, $data['expiry_date'], 0, 1);
            $pdf->SetTextColor(0, 0, 0);

            // QR Code
            if (file_exists($qrLocalPath)) {
                $pdf->Image($qrLocalPath, 30, $pdf->GetY() + 5, 40, 40);
            }

            $pdf->SetY(135);
            $pdf->SetFont('Helvetica', '', 8);
            $pdf->Cell(80, 10, 'Generated by FEMS System', 0, 0, 'C');

            $pdf->Output('F', $path);
        }
        else {
            // Fallback if library missing
            $content = "FPDF Missing. Please ensure helpers/fpdf.php exists.\n";
            $content .= "Serial: " . $data['serial_number'] . "\n";
            file_put_contents($path, $content);
        }

        return '/uploads/labels/' . $filename;
    }
}
